projectTesis/apps/app_prediction/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', prediction, name='index'),
    path('prediction_list/<int:pk>', predictionList, name="prediction_list"),
    path('prediction_create/<int:pk>', predictionCreate, name="prediction_create"),
    path('prediction_detail/<int:pk>', predictionDetail, name="prediction_detail"),
    path('prediction_edit/<int:pk>', predictionEdit, name="prediction_edit"),
    path('prediction_delete/<int:pk>', predictionDelete, name="prediction_delete"),
]

projectTesis/projectTesis/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url 
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),  
    path('',include('apps.app_patient.urls')),
    path('',include('apps.app_prediction.urls')),
    path('',include('apps.app_training_prediction.urls')),
    path('',include('apps.app1.urls')),
) 
urlpatterns += [ 
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("images/favicon.ico"))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectTesis/apps/app_prediction/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.app_patient.models import Patient

sextype = [
    ('F', _('Female')),
    ('M', _('Male')),
]

cpt = [
    ('ASY', _('Asymptomatic')),
    ('ATA', _('Atypical Angina')),
    ('NAP', _('Non-Anginal Pain')),
    ('TA', _('Typical Angina')),
]

recg = [
    ('LVH', 'LVH'),
    ('Normal', 'Normal'),
    ('ST', 'ST'),
]

sts = [
    ('Down', _('DOWN')),
    ('Flat', _('FLAT')),
    ('Up', _('UP')),
]

fbs = [
    (0, _('Blood sugar <= 120 mg/dl')),
    (1, _('Blood sugar > 120 mg/dl')),
]

ea = [
    ('N', 'No'),
    ('Y', _('Yes')),
]

#heartdisease
hd = [
    (0, 'No'),
    (1, _('Yes')),
]
#aimodel
aimod = [
    (0, _('Single Model')),
    (1, _('Ensemble Models')),
]

class Prediction(models.Model):
    date_created = models.DateField(null = True)
    age = models.PositiveIntegerField()
    sex = models.CharField(choices=sextype,max_length=10)
    chestPainType = models.CharField(choices=cpt,max_length=10)
    restingBP = models.PositiveIntegerField()
    cholesterol = models.PositiveIntegerField()
    fastingBS = models.IntegerField(choices=fbs)
    restingECG = models.CharField(choices=recg,max_length=10)
    maxHR = models.PositiveIntegerField()
    exerciseAngina = models.CharField(choices=ea,max_length=10)
    oldpeak = models.DecimalField(max_digits=5, decimal_places=2)
    sT_Slope = models.CharField(choices=sts,max_length=10)
    heartDisease = models.IntegerField(null=True, choices=hd)
    heartDiseaseProb = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    aiModel = models.IntegerField(choices=aimod,max_length=50, null=True)
    Patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return str(self.pk)

projectTesis/apps/app_prediction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .filters import PredictionFilter
from .models import Prediction, Patient
from .forms import PredictionForm, EditPredictionForm, MakePredictionForm, DetailPredictionForm
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
import numpy as np
import pandas as pd
import joblib
import datetime


non_proc_labels = ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']

@login_required(login_url="/login")
def predictionList(request, pk):
    patient = get_object_or_404(Patient,pk=pk,user=request.user)
    #user = request.user
    predictions = Prediction.objects.filter(Patient=patient).order_by('-pk')
    filter = PredictionFilter(request.GET,queryset=predictions)
    predictions = filter.qs
    context = {'pred_list':predictions,'filter':filter,'patient':patient}
    return render(request,"prediction_list.html",context)

@login_required(login_url="/login")
def predictionCreate(request,pk):
    form = MakePredictionForm()
    patient = get_object_or_404(Patient,pk=pk,user=request.user)
    if request.method == 'POST':
        form = MakePredictionForm(request.POST)
        if form.is_valid():        
            #Getting data from post and shaping it to make prediction
            temp = np.array([[
            form.cleaned_data['age'],
            form.cleaned_data['sex'],
            form.cleaned_data['chestPainType'],
            form.cleaned_data['restingBP'],
            form.cleaned_data['cholesterol'],
            form.cleaned_data['fastingBS'],
            form.cleaned_data['restingECG'],
            form.cleaned_data['maxHR'],
            form.cleaned_data['exerciseAngina'],
            form.cleaned_data['oldpeak'],
            form.cleaned_data['sT_Slope'],
            ]])
            temp_pd = pd.DataFrame(temp,columns=non_proc_labels)
            ohEncoder = joblib.load('aiModels/OHEncoder.pkl')
            transformed_temp = ohEncoder.transform(temp_pd)
            sScaler = joblib.load('aiModels/SScaler.pkl')
            sc_transformed_temp = sScaler.transform(transformed_temp)
            aimod = form.cleaned_data['aiModel']
            if aimod == 0 :
                #xgb_class = joblib.load('aiModels/XGBClassifier.pkl')
                mlp_classifier = joblib.load('aiModels/MLPClassifier.pkl')
                hdisease = mlp_classifier.predict(sc_transformed_temp)[0]
                hdProb = mlp_classifier.predict_proba(sc_transformed_temp)[0][1]*100
            else:
                svClassifier = joblib.load('aiModels/SVClassifier.pkl')
                hdisease = svClassifier.predict(sc_transformed_temp)[0]
                hdProb = svClassifier.predict_proba(sc_transformed_temp)[0][1]*100               
            patient = get_object_or_404(Patient,pk=pk)
            prediction = form.save(commit=False)
            prediction.date_created = datetime.date.today()
            prediction.Patient = patient
            prediction.heartDisease = int(hdisease)
            prediction.heartDiseaseProb = hdProb
            patient.last_prediction = int(hdisease)
            patient.last_prediction_prob = hdProb
            patient.save()
            prediction.save()
            return redirect('../prediction_detail'+'/'+str(prediction.pk))
    context = {'form':form,'patient':patient}
    return render(request,'prediction_create.html',context)

@login_required(login_url="/login")
def predictionDetail(request, pk):
    prediction = get_object_or_404(Prediction,pk=pk,Patient__user=request.user)
    form = DetailPredictionForm(instance=prediction)
    context = {"prediction":prediction,"form":form,"patient":prediction.Patient}
    return render(request, 'prediction_detail.html',context)

@login_required(login_url="/login")
def predictionEdit(request, pk):
    prediction = get_object_or_404(Prediction,pk=pk,Patient__user=request.user)
    form = EditPredictionForm(instance=prediction)
    #patient = get_object_or_404(Patient,pk=pk)
    if request.method == 'POST':
        form = EditPredictionForm(request.POST,instance=prediction)
        if form.is_valid():        
            #Getting data from post and shaping it to make prediction
            temp = np.array([[
            form.cleaned_data['age'],
            form.cleaned_data['sex'],
            form.cleaned_data['chestPainType'],
            form.cleaned_data['restingBP'],
            form.cleaned_data['cholesterol'],
            form.cleaned_data['fastingBS'],
            form.cleaned_data['restingECG'],
            form.cleaned_data['maxHR'],
            form.cleaned_data['exerciseAngina'],
            form.cleaned_data['oldpeak'],
            form.cleaned_data['sT_Slope'],
            ]])
            temp_pd = pd.DataFrame(temp,columns=non_proc_labels)
            ohEncoder = joblib.load('aiModels/OHEncoder.pkl')
            transformed_temp = ohEncoder.transform(temp_pd)
            sScaler = joblib.load('aiModels/SScaler.pkl')
            sc_transformed_temp = sScaler.transform(transformed_temp)
            aimod = form.cleaned_data['aiModel']
            if aimod == 0 :
                #xgb_class = joblib.load('aiModels/XGBClassifier.pkl')
                mlp_classifier = joblib.load('aiModels/MLPClassifier.pkl')
                hdisease = mlp_classifier.predict(sc_transformed_temp)[0]
                hdProb = mlp_classifier.predict_proba(sc_transformed_temp)[0][1]*100
            else:
                svClassifier = joblib.load('aiModels/SVClassifier.pkl')
                hdisease = svClassifier.predict(sc_transformed_temp)[0]
                hdProb = svClassifier.predict_proba(sc_transformed_temp)[0][1]*100
            save_as_new = form.cleaned_data['newPrediction']
            prediction = form.save(commit=False)
            pk_patient = prediction.Patient.pk
            if save_as_new:
                patient = get_object_or_404(Patient,pk=pk_patient)
                prediction.pk = None
                prediction._state.adding = True
                prediction.date_created = datetime.date.today()
                prediction.heartDisease = int(hdisease)
                prediction.heartDiseaseProb = hdProb
                prediction.Patient = patient
                patient.last_prediction = int(hdisease)
                patient.last_prediction_prob = hdProb
                patient.save()
            else :
                prediction.heartDisease = int(hdisease)
                prediction.heartDiseaseProb = hdProb
            prediction.save()
            return redirect('../prediction_detail'+'/'+str(prediction.pk))
    context = {"prediction":prediction,"form":form,"patient":prediction.Patient}
    return render(request, 'prediction_edit.html',context)

@login_required(login_url="/login")
def predictionDelete(request, pk):
    prediction = get_object_or_404(Prediction,pk=pk,Patient__user=request.user)
    pat_pk = prediction.Patient.pk
    prediction.delete()
    pred = Prediction.objects.filter(Patient=pat_pk).last()
    last_prediction = pred.heartDisease
    last_prediction_prob = pred.heartDiseaseProb
    patient = patient = get_object_or_404(Patient,pk=pat_pk)
    patient.last_prediction = int(last_prediction)
    patient.last_prediction_prob = last_prediction_prob
    patient.save()
    return redirect('../prediction_list/'+str(pat_pk))

def prediction(request):
    form = PredictionForm()
    hdisease = None
    hdProb = None
    if request.method == 'POST':
        form = PredictionForm(request.POST)
        if form.is_valid():           
            temp = np.array([[
            form.cleaned_data['age'],
            form.cleaned_data['sex'],
            form.cleaned_data['chestPainType'],
            form.cleaned_data['restingBP'],
            form.cleaned_data['cholesterol'],
            form.cleaned_data['fastingBS'],
            form.cleaned_data['restingECG'],
            form.cleaned_data['maxHR'],
            form.cleaned_data['exerciseAngina'],
            form.cleaned_data['oldpeak'],
            form.cleaned_data['sT_Slope'],
            ]])
            temp_pd = pd.DataFrame(temp,columns=non_proc_labels)
            ohEncoder = joblib.load('aiModels/OHEncoder.pkl')
            transformed_temp = ohEncoder.transform(temp_pd)
            sScaler = joblib.load('aiModels/SScaler.pkl')
            sc_transformed_temp = sScaler.transform(transformed_temp)
            aimod = form.cleaned_data['aiModel']
            if aimod == 0 :
                #xgb_class = joblib.load('aiModels/XGBClassifier.pkl')
                mlp_classifier = joblib.load('aiModels/MLPClassifier.pkl')
                hdisease = mlp_classifier.predict(sc_transformed_temp)[0]
                hdProb = mlp_classifier.predict_proba(sc_transformed_temp)[0][1]*100
            else:
                svClassifier = joblib.load('aiModels/SVClassifier.pkl')
                hdisease = svClassifier.predict(sc_transformed_temp)[0]
                hdProb = svClassifier.predict_proba(sc_transformed_temp)[0][1]*100
            hdProb = round(hdProb, 2)
    context = {'form': form,
              'hdisease':hdisease,
              'hdProb':hdProb}
    return render(request, 'prediction.html',context)

projectTesis/apps/app_prediction/templates/prediction.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block titletab %}
<title>{% trans "Prediction" %}</title>
{% endblock titletab %}
{% block title %}
<h1 class="display-4">{% trans "Heart Disease Prediction"%}</h1>
<p class="lead font-italic"></p>
{% endblock title %}
{% block content%}
<h3>{% trans "Please enter details"%}:</h3>
<p class="fs-5">{% trans "Hold the pointer over each filed for details. If you want to know more information about each field, check out the" %} <a href="about_dataset">{% trans 'datasaet'%}</a> {% trans 'in the "About" section'%}.</p>
<br>
<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <div class="container">
        <div class="container-xl px-4 mt-4">
            <div class="row">
                <div class="col-xl-12">
                    <div class="card mb-4">
                        <div class="card-body">
                            <form>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.age|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.sex|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.chestPainType|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.restingBP|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.cholesterol|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.fastingBS|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.restingECG|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.maxHR|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.exerciseAngina|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.oldpeak|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.sT_Slope|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.aiModel|as_crispy_field}}
                                    </div>
                                </div>
                                <hr>
                                <h2>{% trans "Prediction"%}</h2>
                                &nbsp
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        <div id="div_id_heartDisease" class="mb-3 fs-5 text">
                                            <label for="id_heartDisease" class="form-label">
                                                {% trans "Heart Disease"%}: 
                                            </label>
                                            <span class="fw-bold">
                                            {% if hdisease == 0 %}
                                            No
                                            {% elif hdisease == 1 %}
                                            {% trans "Yes"%}
                                            {% endif %}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div id="div_id_heartDiseaseProb" class="mb-3 fs-5 text">
                                            <label for="id_heartDiseaseProb" class="form-label">
                                                {% trans "Probability of heart disease"%}: 
                                            <span class="fw-bold">
                                            {% if hdProb %}
                                            {{hdProb}}%
                                            {% endif %}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        <button class="btn btn-primary" type="Submit">{% trans "Make Prediction"%}</button>
</form>
</div>
</div>
</div>
</div>
</div>
</div>
</form>
{% endblock content%}

projectTesis/apps/app_prediction/templates/prediction_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block titletab %}
<title>{% trans "Create prediction" %}</title>
{% endblock titletab %}
{% block title %}
<h1 class="display-4">{% trans "Make Prediction"%}</h1>
<p class="lead font-italic"></p>
{% endblock title %}
{% block content%}
<div class="row">
    <div class="col text-center">
        <span class="fw-normal fs-3">{% trans "Patient"%}: </span><span class="fst-italic fs-3">{{patient.first_name}} {{patient.last_name}}</span>
    </div>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="container-xl px-4 mt-4">
            <div class="row">
                <div class="col-xl-12">
                    <div class="card mb-4">
                        <div class="card-body">
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.age|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.sex|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.chestPainType|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.restingBP|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.cholesterol|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.fastingBS|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.restingECG|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.maxHR|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.exerciseAngina|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.oldpeak|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.sT_Slope|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.aiModel|as_crispy_field}}
                                    </div>
                                </div>
                                <hr>
                                <h2>{% trans "Prediction"%}</h2>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.heartDisease|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.heartDiseaseProb|as_crispy_field}}
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="d-grid gap-2">
                    <a class="btn btn-primary" href={% url 'patient_list' %}>{% trans "Back to list"%}</a>
                </div>  
            </div>
            <div class="col-md-6">
                <div class="d-grid gap-2">
                    <button class="btn btn-success" type="Submit">{% trans "Make Prediction"%}</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content%}

projectTesis/apps/app_prediction/templates/prediction_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block titletab %}
<title>{% trans "Prediction detail" %}</title>
{% endblock titletab %}
{% block title %}
<h1 class="display-4">{% trans "Prediction Detail"%}</h1>
<p class="lead font-italic"></p>
{% endblock title %}

{% block content%}
<div class="row">
    <div class="col text-center">
        <span class="fw-normal fs-3">{% trans "Patient"%}: </span><span class="fst-italic fs-3">{{patient.first_name}} {{patient.last_name}}</span>
    </div>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="container-xl px-4 mt-4">
            <div class="d-flex flex-row-reverse">
                <div class="p-2">
                    <a href="{% url 'prediction_to_train_add' prediction.pk%}" class="btn btn-outline-success btn-sm">
                        <i class="fas fa-plus"></i> {% trans "Add prediction to model training"%}
                    </a>
                </div>
            </div>
            <div class="row">    
                <div class="col-xl-12">
                    <div class="card mb-4">
                        <div class="card-header">{% trans "Details"%}</div>
                        <div class="card-body">
                            <form>
                                <div class="mb-3">                                   
                                    {{form.date_created|as_crispy_field}}                                     
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.age|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.sex|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.chestPainType|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.restingBP|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.cholesterol|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.fastingBS|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.restingECG|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.maxHR|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.exerciseAngina|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.oldpeak|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.sT_Slope|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.aiModel|as_crispy_field}}
                                    </div>
                                </div>
                                <hr>
                                <h2>{% trans "Prediction"%}</h2>
                                <div class="row gx-3 mb-3">
                                    <div class="col-md-6">
                                        {{form.heartDisease|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.heartDiseaseProb|as_crispy_field}}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="d-grid gap-2">
                <a class="btn btn-primary" href={% url 'prediction_list' patient.pk%}>{% trans "Back to list"%}</a>
            </div>  
        </div>
        <div class="col-md-6">
            <div class="d-grid gap-2">
                <a href="{% url 'prediction_to_train_add' prediction.pk%}" class="btn btn-success">
                    <i class="fas fa-plus"></i> {% trans "Add prediction to model training"%}
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content%}
{% block scripts %}
<!--Chart js-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js" ></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>


{% endblock scripts %}