projectTesis/apps/app1/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
urlpatterns = [
    path('register/', registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('edit_user/', editUser, name="edit_user"),
    path('change_user_pass/', changeUserPass, name="change_user_pass"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),
    path('feature_importance/', featureImportance, name="feature_importance"),
    path('about_ai_models/', aboutAIModels, name="about_ai_models"),
    path('about_dataset/', aboutDataset, name="about_dataset"),
    path('data_analytics/', data_analytics, name="data_analytics"),
]

projectTesis/projectTesis/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url 
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),  
    path('',include('apps.app_patient.urls')),
    path('',include('apps.app_prediction.urls')),
    path('',include('apps.app_training_prediction.urls')),
    path('',include('apps.app1.urls')),
) 
urlpatterns += [ 
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("images/favicon.ico"))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectTesis/apps/app1/forms.py
from random import choices
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')


class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

hd_choices = (
    (0, 'No'),
    (1, _('Yes')),
    (3, _('All')),
)
x_label_choices = (
    (_('Age'), _('Age')),
    (_('RestingBP'), _('RestingBP')),
    (_('Cholesterol'), _('Cholesterol')),
    (_('MaxHR'), _('MaxHR')),
    (_('Oldpeak'), _('Oldpeak')),
)

hue_choices = (
    (_('Sex'), _('Sex')),
    (_('ChestPainType'), _('ChestPainType')),
    (_('FastingBS'), _('FastingBS')),
    (_('RestingECG'), _('RestingECG')),
    (_('ExerciseAngina'), _('ExerciseAngina')),
    (_('ST_Slope'), _('ST_Slope')),
)

bar_choices = (
    (_('Age'), _('Age')),
    (_('Sex'), _('Sex')),
    (_('ChestPainType'), _('ChestPainType')),
    (_('RestingBP'), _('RestingBP')),
    (_('Cholesterol'), _('Cholesterol')),
    (_('FastingBS'), _('FastingBS')),
    (_('RestingECG'), _('RestingECG')),
    (_('MaxHR'), _('MaxHR')),
    (_('ExerciseAngina'), _('ExerciseAngina')),
    (_('Oldpeak'), _('Oldpeak')),
    (_('ST_Slope'), _('ST_Slope')),
)

class DataAnalyticsBoxForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(DataAnalyticsBoxForm, self).__init__(*args, **kwargs)   
        self.fields['output_box'].label = _('Heart Disease')
        self.fields['x_label_box'].label = _('Variable (X Axis)')
        self.fields['hue_box'].label = _('Groups')  

    output_box = forms.ChoiceField(choices=hd_choices, required=False)
    x_label_box = forms.ChoiceField(choices=x_label_choices, required=False)
    hue_box = forms.ChoiceField(choices=hue_choices, required=False)

class DataAnalyticsHistForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(DataAnalyticsHistForm, self).__init__(*args, **kwargs)   
        self.fields['output'].label = _('Heart Disease')
        self.fields['x_label'].label = _('Variable (X Axis)')
        self.fields['hue'].label = _('Groups')  

    output = forms.ChoiceField(choices=hd_choices, required=False)
    x_label = forms.ChoiceField(choices=x_label_choices, required=False)
    hue = forms.ChoiceField(choices=hue_choices, required=False)

class DataAnalyticsBarsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(DataAnalyticsBarsForm, self).__init__(*args, **kwargs)   
        self.fields['output_bar'].label = _('Heart Disease')
        self.fields['x_label_bar'].label = _('Variable (X Axis)')

    output_bar = forms.ChoiceField(choices=hd_choices, required=False)
    x_label_bar = forms.ChoiceField(choices=bar_choices, required=False)

projectTesis/apps/app1/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, EditUserForm, DataAnalyticsHistForm,DataAnalyticsBarsForm,DataAnalyticsBoxForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from apps.app_training_prediction.models import PredictionToTrain
import pandas as pd
import numpy as np
import joblib
import json
from plotly.offline import plot
import plotly.express as px



def registerPage(request):
    if request.user.is_authenticated:
        return redirect('Prediction')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request,_('Account was created for ')+user)
                return redirect('login')
        context = {'form':form}
        return render(request,'register.html',context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.info(request, _('Username or Password is incorrect'))
        context = {}
        return render(request,'login.html',context)

@login_required(login_url="/login")
def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url="/login")
def editUser(request):
    form = EditUserForm(instance = request.user)
    print(request.user)
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,_('Account was updated for ')+user)
            #return redirect('prediction')
    context = {'form':form}
    return render(request,'edit_user.html',context)

@login_required(login_url="/login")
def changeUserPass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user, data=request.POST)
            #form = PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                return redirect('Prediction')
        else:
            form = PasswordChangeForm(user=request.user)
        context = {'form':form}
        return render(request,'change_user_pass.html',context)


def featureImportance(request):
    proc_labels = [_('Sex_F'), _('Sex_M'),
       _('ChestPainType_ASY'),_('ChestPainType_ATA'),_('ChestPainType_NAP'),_('ChestPainType_TA'), _('RestingECG_LVH'),
       _('RestingECG_Normal'), _('RestingECG_ST'),
       _('ExerciseAngina_N'),_('ExerciseAngina_Y'), 
       _('ST_Slope_Down'),_('ST_Slope_Flat'), _('ST_Slope_Up'),
       _('Age'), _('RestingBP'), _('Cholesterol'),
       _('FastingBS'), _('MaxHR'), _('Oldpeak')]
    xgb_class = joblib.load('aiModels/XGBClassifier.pkl')
    f_importances = np.round(xgb_class.feature_importances_*100,2)

    feat_dict = {}
    for i in range(len(f_importances)):
        feat_dict[proc_labels[i]] = f_importances[i]
    feat_dict
    sorted_feat_dict = {k: v for k, v in sorted(feat_dict.items(), key=lambda item: item[1],reverse=True)}
    sort_f_importances = []
    labels = []
    for key in sorted_feat_dict:
        if feat_dict[key] > 0:
            sort_f_importances += [feat_dict[key]]
            labels += [key]
    main_label = _('Feature Importance %')
    context = {'f_importances':sort_f_importances,
                'labels':labels,
                'main_label':main_label}
    return render(request, 'feature_importance.html',context)

def aboutAIModels(request):
    return render(request, 'about_ai_models.html')

def aboutDataset(request):
    non_proc_lab = [_('Age'), _('Sex'), _('ChestPainType'), _('RestingBP'), _('Cholesterol'), _('FastingBS'),
        _('RestingECG'), _('MaxHR'), _('ExerciseAngina'), _('Oldpeak'), _('ST_Slope'), _('HeartDisease')]
    proc_labels = ['Sex_F', 'Sex_M',
        'ChestPainType_ASY','ChestPainType_ATA','ChestPainType_NAP','ChestPainType_TA', 'RestingECG_LVH',
        'RestingECG_Normal', 'RestingECG_ST',
        'ExerciseAngina_N','ExerciseAngina_Y', 
        'ST_Slope_Down','ST_Slope_Flat', 'ST_Slope_Up',
        'Age', 'RestingBP', 'Cholesterol',
        'FastingBS', 'MaxHR', 'Oldpeak',
        'HeartDisease']
    template_proc_labels = [_('Sex_F'), _('Sex_M'),
        _('ChestPainType_ASY'),_('ChestPainType_ATA'),_('ChestPainType_NAP'),_('ChestPainType_TA'), _('RestingECG_LVH'),
        _('RestingECG_Normal'), _('RestingECG_ST'),
        _('ExerciseAngina_N'),_('ExerciseAngina_Y'), 
        _('ST_Slope_Down'),_('ST_Slope_Flat'), _('ST_Slope_Up'),
        _('Age'), _('RestingBP'), _('Cholesterol'),
        _('FastingBS'), _('MaxHR'), _('Oldpeak'),
        _('HeartDisease')]
    df = pd.read_csv("apps/app1/static/app1/Data/heart.csv")
    df = df.head(20)
    json_rec = df.reset_index().to_json(orient='records')
    arr = []
    arr = json.loads(json_rec)
    ohEncoderOriginal = joblib.load('aiModels/OHEncoderOriginal.pkl')
    transformed_df = ohEncoderOriginal.transform(df)
    encoded_pd = pd.DataFrame(transformed_df, columns=proc_labels)
    json_rec_encoded = encoded_pd.reset_index().to_json(orient='records')
    arr_encoded = []
    arr_encoded = json.loads(json_rec_encoded)
    context = {"arr":arr,
              "non_proc_lab":non_proc_lab,
              "arr_encoded":arr_encoded,
              "proc_labels":proc_labels,
              "template_proc_labels":template_proc_labels}
    return render(request, 'about_dataset.html',context)

@login_required(login_url="/login")
def data_analytics(request):
    qs = PredictionToTrain.objects.all()
    predictions_data = [
        {
           _('Age') :  i.age,
           _('Sex') :  i.sex,
           _('ChestPainType') :  i.chestPainType,
           _('RestingBP') :  i.restingBP,
           _('Cholesterol') :  i.cholesterol,
           _('FastingBS') :  i.fastingBS,
           _('RestingECG') :  i.restingECG,
           _('MaxHR') :  i.maxHR,
           _('ExerciseAngina') :  i.exerciseAngina,
           _('Oldpeak') :  i.oldpeak,
           _('ST_Slope') :  i.sT_Slope,
           _('HeartDisease') :  i.heartDisease,
        } for i in qs
    ]
    df = pd.DataFrame(predictions_data)
    #BoxPLot
    output_box = request.GET.get('output_box')
    x_label_box = request.GET.get('x_label_box')
    hue_box = request.GET.get('hue_box')
    box_output = 0
    box_x = _('Age')
    box_hue = _('Sex')
    if output_box:
        box_output = output_box
    if x_label_box:
        box_x = x_label_box
    if hue_box:
        box_hue = hue_box
    df_box = df[df[_('HeartDisease')]==int(box_output)]
    if int(box_output) == 3:
        df_box = df
    fig_box = px.box(df_box, x=box_x,color=box_hue,
                         notched=True, hover_data=df.columns).update_layout(
                             yaxis_title=_('Heart Disease Output (Total)'),
                             height=700
                         )
    gantt_plot_box = plot(fig_box, output_type="div") 
    #1st Histogram
    output_hist = request.GET.get('output')
    x_label_hist = request.GET.get('x_label')
    hue_hist = request.GET.get('hue')
    hist_output = 0
    hist_x = _('Age')
    hist_hue = _('Sex')
    if output_hist:
        hist_output = output_hist
    if x_label_hist:
        hist_x = x_label_hist
    if hue_hist:
        hist_hue = hue_hist
    df_hist = df[df[_('HeartDisease')]==int(hist_output)]
    if int(hist_output) == 3:
        df_hist = df
    fig_hist = px.histogram(df_hist, x=hist_x,color=hist_hue,
                         marginal="rug", hover_data=df.columns).update_layout(
                             yaxis_title=_('Heart Disease Output (Total)'),
                             height=700
                         )
    gantt_plot_hist = plot(fig_hist, output_type="div")
    #2nd Histogram
    output_bar = request.GET.get('output_bar')
    x_label_bar = request.GET.get('x_label_bar')
    bar_output = 0
    bar_x = _('Age')
    if output_bar:
        bar_output = output_bar
    if x_label_bar:
        bar_x = x_label_bar
    df_bar = df[df[_('HeartDisease')]==int(bar_output)]
    if int(bar_output) == 3:
        df_bar = df
    fig_bar = px.histogram(df_bar, x=bar_x,
                         marginal="rug", hover_data=df.columns).update_layout(
                             yaxis_title=_('Heart Disease Output (Total)'),
                             height=700
                         )
    gantt_plot_bar = plot(fig_bar, output_type="div")

    context = {'plot_div_box':gantt_plot_box,
               'plot_div_hist': gantt_plot_hist,
               'plot_div_bar': gantt_plot_bar,
               'form_box':DataAnalyticsBoxForm(request.GET),
               'form_bar':DataAnalyticsBarsForm(request.GET),
               'form_hist':DataAnalyticsHistForm(request.GET)}
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        #BoxPlot
        output_box = request.GET.get('output_box')
        x_label_box = request.GET.get('x_label_box')
        hue_box = request.GET.get('hue_box')
        box_output = 0
        box_x = _('Age')
        box_hue = _('Sex')
        if output_box:

projectTesis/apps/app1/templates/base.html
{% load i18n %}
{% load replace %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <!-- Bootstrap CSS -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    {% block titletab %}
    <title>{% trans "Hello, world" %}!</title>
    {% endblock titletab %}
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container-fluid">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="p-5 mb-4 bg-light rounded-3">
                {% block title %}
                {% endblock title %}
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    <hr>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_language_info for LANGUAGE_CODE as lang_info %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="container">
        <div class="row">
            <div class="col md-3 offset-md-11">
                <div class="dropdown">
                    <button class="btn btn-outline-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-globe">&nbsp</i>{{lang_info.name_local}}
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        {% for lang in languages %}
                        {% if lang.code == 'es' or lang.code == 'en' %}
                        <li >
                            <a class="dropdown-item" href="/{{lang.code}}{{request.path|replace}}">
                                {{lang.name_local}}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                  </div>
            </div>
        </div>
    </div>
    &nbsp
</body>


{%block scripts%}
{%endblock scripts%}
</html>

projectTesis/apps/app1/templates/change_user_pass.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block titletab %}
<title>{% trans "Change password" %}</title>
{% endblock titletab %}
{% block title %}
<h1 class="display-4">{% trans "Change Password"%}</h1>
<p class="lead font-italic"></p>
{% endblock title %}
{% block content%}
<form action="" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            {{form.old_password|as_crispy_field}}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{form.new_password1|as_crispy_field}}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{form.new_password2 |as_crispy_field}}
        </div>
    </div>
    &nbsp
    <div class="row">
        <div class="d-grid gap-1 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">{% trans "Update Password"%}</button>
    
        </div>
    </div>
</form>
{% endblock content%}

projectTesis/apps/app1/templates/data_analytics.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block titletab %}
<title>{% trans "Data Analytics" %}</title>
{% endblock titletab %}
{% block title %}
<h1 class="display-4 text-center">{% trans "Data Analytics"%}</h1>
<p class="lead font-italic"></p>
{% endblock title %}
{% block content%}
<p class="fs-5">{% trans "In this section you will be able to perform a visual analysis on the data that was used to train the model and the subsequently added data. If you want to check more information about the dataset and its features click "%}<a href={% url 'about_dataset' %} class="fs-5">{% trans "here"%}</a>.</p>
<p class="fs-5">{% trans "The following boxplot provides a standardized way of displaying the distribution of data based on a five number summary : minimum, first quartile (Q1), median, third quartile (Q3), and maximum. It lets you navigate through variables for the x axis, which are the numerical features of the dataset; the groups , which are the categorical features of the dataset and the output class."%}</p>
&nbsp
<form action="" method="GET">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {{form_box.x_label_box|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form_box.hue_box|as_crispy_field}}
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-md-12">
                {{form_box.output_box|as_crispy_field}}
            </div>
        </div>
    </div>
</form>
    {% autoescape off %}
    <div id="box_plot_id">
        {{plot_div_box}}
    </div>   
    {% endautoescape %}
&nbsp
&nbsp
<p class="fs-5">{% trans "The following histogram lets you navigate through variables for the x axis, which are the numerical features of the dataset; the groups , which are the categorical features of the dataset and the output class."%}</p>
&nbsp
<form action="" method="GET">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {{form_hist.x_label|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form_hist.hue|as_crispy_field}}
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-md-12">
                {{form_hist.output|as_crispy_field}}
            </div>
        </div>
    </div>
</form>
    {% autoescape off %}
    <div id="hist_1_plot_id">
        {{plot_div_hist}}
    </div>
    {% endautoescape %}
&nbsp
&nbsp
<p class="fs-5">{% trans "The following histogram lets you navigate through the variables for the x axis, wich are all the features in the dataset, and the output class, analyze the correlation between each feature and the output class."%}</p>
&nbsp
<form action="" method="GET">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                {{form_bar.output_bar|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form_bar.x_label_bar|as_crispy_field}}
            </div>
        </div>
    </div>
</form>
    {% autoescape off %}
    <div id="hist_2_plot_id">
        {{plot_div_bar}}
    </div>
    {% endautoescape %}
{% endblock content%}
{% block scripts %}
<script>
    //Box Plot
    $("#id_x_label_box").change(function () {
      var x_label_box = $(this).val();
      var output_box = $("#id_output_box").val();
      var hue_box = $("#id_hue_box").val();
      $.ajax({
        url: '{% url "data_analytics" %}',
        type: 'GET',
        data: {
          'x_label_box': x_label_box,
          'hue_box': hue_box,
          'output_box': output_box,
        },
        dataType: 'json',
        success: function (response) {
            console.log(response.gantt_plot_box);
            $("#box_plot_id").html(response.gantt_plot_box);
          }
      });
    });
    $("#id_output_box").change(function () {
        var x_label_box = $("#id_x_label_box").val();
        var output_box = $(this).val();
        var hue_box = $("#id_hue_box").val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label_box': x_label_box,
            'hue_box': hue_box,
            'output_box': output_box,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_box);
              $("#box_plot_id").html(response.gantt_plot_box);
            }
        });
      });
      $("#id_hue_box").change(function () {
        var x_label_box = $("#id_x_label_box").val();
        var output_box = $("#id_output_box").val();
        var hue_box = $(this).val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label_box': x_label_box,
            'hue_box': hue_box,
            'output_box': output_box,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_box);
              $("#box_plot_id").html(response.gantt_plot_box);
            }
        });
      });
      //First Histogram
      $("#id_x_label").change(function () {
        var x_label = $(this).val();
        var output = $("#id_output").val();
        var hue = $("#id_hue").val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label': x_label,
            'hue': hue,
            'output': output,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_hist);
              $("#hist_1_plot_id").html(response.gantt_plot_hist);
            }
        });
      });
      $("#id_output").change(function () {
        var x_label = $("#id_x_label").val();
        var output = $(this).val();
        var hue = $("#id_hue").val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label': x_label,
            'hue': hue,
            'output': output,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_hist);
              $("#hist_1_plot_id").html(response.gantt_plot_hist);
            }
        });
      });
      $("#id_hue").change(function () {
        var x_label = $("#id_x_label").val();
        var output = $("#id_output").val();
        var hue = $(this).val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label': x_label,
            'hue': hue,
            'output': output,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_hist);
              $("#hist_1_plot_id").html(response.gantt_plot_hist);
            }
        });
      });
    //Second Histogram
    $("#id_x_label_bar").change(function () {
        var x_label_bar = $(this).val();
        var output_bar = $("#id_output_bar").val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label_bar': x_label_bar,
            'output_bar': output_bar,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_bar);
              $("#hist_2_plot_id").html(response.gantt_plot_bar);
            }
        });
      });
      $("#id_output_bar").change(function () {
        var x_label_bar = $("#id_x_label_bar").val();
        var output_bar = $(this).val();
        $.ajax({
          url: '{% url "data_analytics" %}',
          type: 'GET',
          data: {
            'x_label_bar': x_label_bar,
            'output_bar': output_bar,
          },
          dataType: 'json',
          success: function (response) {
              console.log(response.gantt_plot_bar);
              $("#hist_2_plot_id").html(response.gantt_plot_bar);
            }
        });
      });
  </script>
{% endblock scripts %}

projectTesis/apps/app1/templates/password_reset.html
{% extends 'base_user.html' %}
{% load i18n %}
{% load static %}
{% load replace %}
{% block titletab %}
<title>{% trans "Password reset" %}</title>
{% endblock titletab %}
            {% block content %}
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <img src="{% static 'images/logo.png' %}"
                      style="width: 185px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">Heart Help App</h4>
                  </div>
  
                  <form method="POST" class="text-center">
                      {% csrf_token %}
                    <p>{% trans "Forgotten your password? Enter your email adress below and we will email instructions to set a new one."%}</p>
  
                    <div class="form-outline mb-4">
                        {{form}}
                    </div>
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-secondary btn-block mb-3" type="submit">{% trans "Send email" %}</button>
                    </div>
                    {% for message in messages %}
                        <p id="">{{message}}</p>
                    {% endfor %}
                  </form>
                </div>
              </div>
              </div>
            </div>      
            {% endblock content %} 